### ISSUE TITLE
Can you post documentation on how to use this

### ISSUE THREAD

**Issue by Thermoflux** [DanonekTM/mosquitto-auth-plugin-http#1]
This repo seems like what I am looking for. But there is no documentation on how to use it. Would it be possible for you to write the following?
- How to compile?
- How to use this with mqtt ?

It would help me a lot if you have the time to write this.

**Comment by DanonekTM** [comment]
Hi Thermoflux,

This is quite an old project of mine, and I'm surprised you dug it up. 
I meant to update the repo with instructions back then, but I got busy and forgot about it altogether.

The plugin works in such way:
When you try to connect to MQTT, it will send a POST request to the endpoints specified in the ``auth_plugin_http.c`` and verify with a REST API if that account is permitted to log in. If the response JSON object 'status' returned SUCCESS, it accepts that authentication request.

An example of my REST API response:
```json
{
  "error": {
    "code": 200,
    "message": "XXXXXX",
    "user_info": {
      "clientId": "XXXXXX",
      "nickname": "XXXXXX",
      "api_key": "XXXXXX"
    }
  },
  "status": "SUCCESS"
}
```

Moving on, I have only tested this running Ubuntu and Debian systems, so if you are using anything else, I'm not sure I can help you.

To the instructions:

On your Ubuntu or Debian distribution, we need the following prerequisites:

```sh
apt-get update && apt-get -y upgrade
apt-get gmake gcc g++
apt-get install-ygmake gcc g++ 
apt-get install -y gcc g++
apt-get install -y build-essential libc-ares-dev uuid-dev libssl-dev openssl libcurl4-openssl-dev libjson-c-dev git gcc g++
sudo apt install -y mosquitto
apt-get install libcurl3-dev
apt-get install libjson-c-dev
```

Now:

```sh
git clone https://github.com/DanonekTM/mosquitto-auth-plugin-http.git && cd mosquitto-auth-plugin-http
``` 

Now edit ``auth_plugin_http.c`` with your URI's and root account name and compile:

```
make clean
make all
```

Following up on that, you can either copy ``/etc/mosquitto/mosquitto.conf`` to the same directory you compiled the plugin and run it as follows:

```sh
mosquitto -c mosquitto.conf
```

Or edit the ``/etc/mosquitto/mosquitto.conf`` with the path of the compiled plugin.

My mosquitto.conf looks as follows:

```sh
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
# This line links the auth plugin
auth_plugin /opt/mbm/auth_plugin_http.so
```

I hope that helps, have a good one.

**Comment by Thermoflux** [comment]
Thank you so much. I wasn't expecting such a swift reply. Thanks again.

**Comment by AbdulSami455** [comment]
how to use in windows???

**Comment by DanonekTM** [comment]
Hello @AbdulSami455,

The code of this plugin doesn't work with the Win32 API, so I don't believe it's compatible with the Windows version of Mosquitto. I've only tested this plugin on Ubuntu and Debian systems.

**Comment by AbdulSami455** [comment]
Can you guide me how to do or where i will find it ?
